import { useEffect, useMemo, useState } from 'react'
import { X } from './Icons'
import { supabase } from '../lib/supabase'

type UserRow = { id:string; full_name:string|null; email:string|null; role:string; status:string; class_level:string|null; access_mode:string; daily_credit_limit:number; bonus_credits:number; bonus_expires_on:string|null; created_at:string; last_sign_in_at:string|null }
type RequestRow = { id:number; user_id:string; message:string|null; requested_credits:number|null; status:string; admin_note:string|null; created_at:string; reviewed_at:string|null; user?: { full_name?:string|null; email?:string|null; class_level?:string|null; status?:string; role?:string } }
type Stats = { totalUsers:number; activeUsers:number; restrictedUsers:number; requestsToday:number }
type AuditRow = { id:number; action:string; target_user_id:string|null; details:any; created_at:string }

export function AdminModal({onClose}:{onClose:()=>void}){
 const [tab,setTab]=useState<'overview'|'users'|'requests'|'audit'>('overview')
 const [users,setUsers]=useState<UserRow[]>([]),[requests,setRequests]=useState<RequestRow[]>([]),[audit,setAudit]=useState<AuditRow[]>([]),[stats,setStats]=useState<Stats|null>(null)
 const [query,setQuery]=useState(''),[busy,setBusy]=useState(true),[error,setError]=useState('')
 async function call(body:any){if(!supabase)throw new Error('Supabase is not configured.');const {data,error}=await supabase.functions.invoke('rafaai-admin',{body});if(error)throw error;return data}
 async function load(){setBusy(true);setError('');try{const [u,r,s,a]=await Promise.all([call({action:'list_users',page:1,pageSize:100}),call({action:'list_access_requests',page:1,pageSize:100}),call({action:'get_stats'}),call({action:'get_audit',limit:50})]);setUsers((u.users||[]).filter((user:UserRow)=>user.role!=='admin'));setRequests(r.requests||[]);setStats(s.stats||null);setAudit(a.audit||[])}catch(e:any){setError(e?.message||'Could not load admin data.')}finally{setBusy(false)}}
 useEffect(()=>{load()},[])
 async function setAccess(userId:string,type:string){try{const body:any={action:'set_access',userId,accessType:type};if(type==='today_bonus'){const v=window.prompt('Extra credits for today','50');if(v===null)return;body.bonusCredits=Number(v)}if(type==='permanent'){const v=window.prompt('Permanent daily AI credit limit','50');if(v===null)return;body.dailyCreditLimit=Number(v)}await call(body);await load()}catch(e:any){setError(e?.message||'Could not update access.')}}
 async function setStatus(userId:string,status:'active'|'restricted'){if(status==='restricted'&&!window.confirm('Ban/restrict this account from using RafaAi?'))return;try{await call({action:'set_status',userId,status});await load()}catch(e:any){setError(e?.message||'Could not update account status.')}}
 async function setRole(userId:string,role:'admin'|'student'){if(role==='admin'&&!window.confirm('Give this account full RafaAi Admin access?'))return;try{await call({action:'set_role',userId,role});await load()}catch(e:any){setError(e?.message||'Could not update account role.')}}
 async function review(id:number,decision:'approved'|'rejected'){const note=window.prompt(decision==='approved'?'Optional admin note. Approval will grant the requested daily credits.':'Optional reason for rejection.','')??'';try{await call({action:'review_access_request',requestId:id,decision,adminNote:note});await load()}catch(e:any){setError(e?.message||'Could not review request.')}}
 const visibleUsers=useMemo(()=>users.filter(u=>u.role!=='admin'),[users])
 const filteredUsers=useMemo(()=>{const q=query.trim().toLowerCase();if(!q)return visibleUsers;return visibleUsers.filter(u=>[u.full_name,u.email,u.role,u.status,u.class_level].filter(Boolean).some(v=>String(v).toLowerCase().includes(q)))},[visibleUsers,query])
 const pending=requests.filter(r=>r.status==='pending').length
 return <div className="modal-backdrop admin-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)onClose()}}><div className="admin-card admin-dashboard">
  <div className="admin-head"><div><div className="eyebrow">RAFAAI ADMIN CONSOLE</div><h2>Admin Dashboard</h2><p className="settings-subtitle">Users, access, credits, requests and account controls.</p></div><button className="modal-close" onClick={onClose} aria-label="Close"><X/></button></div>
  <div className="admin-tabs"><button className={tab==='overview'?'active':''} onClick={()=>setTab('overview')}>Overview</button><button className={tab==='users'?'active':''} onClick={()=>setTab('users')}>Users <b>{visibleUsers.length}</b></button><button className={tab==='requests'?'active':''} onClick={()=>setTab('requests')}>Requests {pending>0&&<b>{pending}</b>}</button><button className={tab==='audit'?'active':''} onClick={()=>setTab('audit')}>Audit log</button></div>
  {error&&<div className="form-error">{error}</div>}{busy?<div className="admin-empty">Loading admin data…</div>:<>
   {tab==='overview'&&<div className="admin-overview"><div className="admin-stat-grid"><div className="admin-stat"><span>Total users</span><strong>{stats?.totalUsers??0}</strong></div><div className="admin-stat"><span>Active</span><strong>{stats?.activeUsers??0}</strong></div><div className="admin-stat"><span>Restricted</span><strong>{stats?.restrictedUsers??0}</strong></div><div className="admin-stat"><span>Requests today</span><strong>{stats?.requestsToday??0}</strong></div></div><div className="admin-overview-grid"><div className="admin-info-card"><b>Pending access requests</b><strong>{pending}</strong><span>Approve a request to grant its requested daily credit limit.</span><button onClick={()=>setTab('requests')}>Open requests →</button></div><div className="admin-info-card"><b>Account controls</b><strong>Full control</strong><span>Manage credits, ban/unban accounts, and assign Admin or Student roles.</span><button onClick={()=>setTab('users')}>Manage users →</button></div></div></div>}
   {tab==='users'&&<div className="admin-section"><div className="admin-toolbar"><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search name, Gmail, role or status…"/><button onClick={load}>Refresh</button></div><div className="admin-user-list">{filteredUsers.map(u=><div className="admin-user-card" key={u.id}><div className="admin-user-main"><div className="admin-avatar">{(u.full_name||u.email||'U').slice(0,1).toUpperCase()}</div><div className="admin-user-copy"><div className="admin-user-title"><b>{u.full_name||'Unnamed user'}</b><span className={u.status==='restricted'?'status-badge restricted':'status-badge'}>{u.status==='restricted'?'BANNED':'ACTIVE'}</span><span className="role-badge">{u.role}</span></div><span className="admin-email">{u.email||'Gmail unavailable'}</span><small>{u.class_level||'No class'} · Joined {new Date(u.created_at).toLocaleDateString('en-IN')} {u.last_sign_in_at?'· Last login '+new Date(u.last_sign_in_at).toLocaleString('en-IN'):''}</small></div></div><div className="admin-credit-row"><span><b>{u.access_mode==='unlimited'?'∞':u.daily_credit_limit}</b>/day</span>{u.bonus_credits>0&&<span>+{u.bonus_credits} today</span>}<span>{u.access_mode}</span></div><div className="admin-control-grid"><button onClick={()=>setAccess(u.id,'today_bonus')}>+ Today</button><button onClick={()=>setAccess(u.id,'permanent')}>Set daily</button><button onClick={()=>setAccess(u.id,'unlimited')}>Unlimited</button><button onClick={()=>setAccess(u.id,'standard')}>20/day</button>{u.status==='restricted'?<button className="success-action" onClick={()=>setStatus(u.id,'active')}>Unban</button>:<button className="danger-action" onClick={()=>setStatus(u.id,'restricted')}>Ban</button>}{u.role==='admin'?<button onClick={()=>setRole(u.id,'student')}>Make student</button>:<button onClick={()=>setRole(u.id,'admin')}>Make admin</button>}</div></div>)}{filteredUsers.length===0&&<div className="admin-empty">No matching users.</div>}</div></div>}
   {tab==='requests'&&<div className="admin-section">{requests.length===0?<div className="admin-empty">No access requests yet.</div>:<div className="admin-request-list">{requests.map(r=><div className="admin-request-card" key={r.id}><div className="request-top"><div><b>Request #{r.id}</b><span className={r.status==='pending'?'request-pending':'request-status'}>{r.status}</span></div><small>{new Date(r.created_at).toLocaleString('en-IN')}</small></div><div className="request-user"><div className="admin-avatar">{(r.user?.full_name||r.user?.email||'U').slice(0,1).toUpperCase()}</div><div><b>{r.user?.full_name||'Unnamed user'}</b><span>{r.user?.email||'Gmail unavailable'}</span><small>{r.user?.class_level||'No class'} · {r.user?.status||'unknown'} · {r.user?.role||'student'}</small></div></div><div className="request-message"><b>Message</b><p>{r.message||'No message provided.'}</p></div><div className="request-credit"><span>Requested daily credits</span><strong>{r.requested_credits??'Not specified'}</strong></div>{r.admin_note&&<div className="request-note"><b>Admin note</b><p>{r.admin_note}</p></div>}{r.status==='pending'&&<div className="admin-request-actions"><button className="approve-action" onClick={()=>review(r.id,'approved')}>Approve & grant</button><button className="danger-action" onClick={()=>review(r.id,'rejected')}>Reject</button></div>}</div>)}</div>}</div>}
   {tab==='audit'&&<div className="admin-section"><div className="audit-list">{audit.map(a=><div className="audit-row" key={a.id}><div><b>{a.action}</b><span>{a.target_user_id?'Target: '+a.target_user_id:'System action'}</span></div><small>{new Date(a.created_at).toLocaleString('en-IN')}</small></div>)}</div></div>}
  </>}</div></div>
}