import { useEffect, useState } from 'react'
import { X } from './Icons'
import { supabase } from '../lib/supabase'
type UserRow={id:string;full_name:string|null;role:string;status:string;created_at:string}
type RequestRow={id:number;user_id:string;message:string|null;requested_credits:number|null;status:string;created_at:string}
export function AdminModal({onClose}:{onClose:()=>void}){
 const [users,setUsers]=useState<UserRow[]>([]),[requests,setRequests]=useState<RequestRow[]>([]),[tab,setTab]=useState<'users'|'requests'>('users'),[busy,setBusy]=useState(true),[error,setError]=useState('')
 async function call(body:any){const {data,error}=await supabase!.functions.invoke('rafaai-admin',{body});if(error)throw error;return data}
 async function load(){setBusy(true);setError('');try{const [u,r]=await Promise.all([call({action:'list_users'}),call({action:'list_access_requests'})]);setUsers(u.users||[]);setRequests(r.requests||[])}catch(e:any){setError(e?.message||'Could not load admin data.')}finally{setBusy(false)}}
 useEffect(()=>{load()},[])
 async function setAccess(userId:string,type:string){let body:any={action:'set_access',userId,accessType:type};if(type==='today_bonus')body.bonusCredits=Number(window.prompt('Bonus credits for today','50')||'0');if(type==='permanent')body.dailyCreditLimit=Number(window.prompt('Permanent daily credits','50')||'0');try{await call(body);await load()}catch(e:any){setError(e?.message||'Could not update access.')}}
 async function review(id:number,decision:'approved'|'rejected'){try{await call({action:'review_access_request',requestId:id,decision});await load()}catch(e:any){setError(e?.message||'Could not review request.')}}
 return <div className="modal-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)onClose()}}><div className="admin-card"><div className="settings-head"><div><div className="eyebrow">RAFAAI ADMIN</div><h2>Access control</h2><p className="settings-subtitle">Manage student credits and access requests.</p></div><button className="modal-close" onClick={onClose}><X/></button></div><div className="settings-tabs"><button className={tab==='users'?'active':''} onClick={()=>setTab('users')}>Users</button><button className={tab==='requests'?'active':''} onClick={()=>setTab('requests')}>Requests {requests.filter(r=>r.status==='pending').length?('('+requests.filter(r=>r.status==='pending').length+')'):''}</button></div>{error&&<div className="form-error">{error}</div>}{busy?<div className="admin-empty">Loading…</div>:tab==='users'?<div className="admin-list">{users.map(u=><div className="admin-user" key={u.id}><div><b>{u.full_name||'Unnamed student'}</b><span>{u.role} · {u.status}</span></div><div className="admin-actions"><button onClick={()=>setAccess(u.id,'today_bonus')}>+ Today</button><button onClick={()=>setAccess(u.id,'permanent')}>Set daily</button><button onClick={()=>setAccess(u.id,'unlimited')}>Unlimited</button><button onClick={()=>setAccess(u.id,'standard')}>20/day</button></div></div>)}</div>:<div className="admin-list">{requests.length===0?<div className="admin-empty">No access requests yet.</div>:requests.map(r=><div className="admin-request" key={r.id}><div><b>Request #{r.id}</b><span>{r.message||'No message'}{r.requested_credits?(' · Requested '+r.requested_credits+'/day'):''}</span><small>{new Date(r.created_at).toLocaleString('en-IN')}</small></div>{r.status==='pending'&&<div className="admin-actions"><button onClick={()=>review(r.id,'approved')}>Approve</button><button onClick={()=>review(r.id,'rejected')}>Reject</button></div>}</div>)}</div>}</div></div>
}